# Copyright © 2010 Andrew D. Yates
# https://github.com/andrewdyates/twdmailer

application: twdmailer
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:

- url: /static
  static_dir: static

- url: /_ah/login_required
  script: do_openid_login.py
  
- url: /logged_out
  script: logged_out.py

- url: /?
  script: main.py
  login: required

- url: /super/?.*
  script: super.py
  login: admin

- url: /user/?.*
  script: user.py
  login: required

- url: /submit/?.*
  script: submit.py


# Cron Automated Jobs, see cron.yaml
- url: /cron/?.*
  script: cron.py
  login: admin

# Developer Testing
- url: /test/?.*
  script: test.py
  login: admin
