# Copyright © 2010 Andrew D. Yates
# https://github.com/andrewdyates/twdmailer

application: twdmailer
version: 1
runtime: python
api_version: 1

handlers:

# Authentication
- url: /_ah/login_required
  script: do_openid_login.py
- url: /logged_out
  script: logged_out.py

# Super
- url: /super/?.*
  script: super.py
  login: admin
  
# Admin
- url: /admin/?.*
  script: admin.py
  login: required

# User
- url: /user/?.*
  script: user.py
  login: required

# Submission
- url: /submit/?.*
  script: submit.py

# Home
- url: /
  script: main.py

# Cron Automated Jobs, see cron.yaml
- url: /cron/?.*
  login: admin
  script: cron.py

# Developer Testing
- url: /test/?.*
  login: admin
  script: test.py