# Copyright © 2010 Andrew D. Yates
# https://github.com/andrewdyates/twdmailer

application: twdmailer
version: 1
runtime: python
api_version: 1

handlers:

- url: /_ah/login_required
  script: do_openid_login.py

- url: /logged_out
  script: logged_out.py
  
- url: /.*
  script: main.py
  login: required
  

